Repository team-moeum/rn-boilerplate, pull requests merged in 2025-01, with the labels that each got.

#23 [Feat/#22] preview 배포 스크립트 테스트
  .env.example
  .github/workflows/develop-cd.yml
  .github/workflows/label-checker.yml
  .github/workflows/notify-slack.yml
  .github/workflows/prepare.yml
  .github/workflows/preview-cd.yml
  .github/workflows/production-cd.yml
  app.config.js
  package.json
  pnpm-lock.yaml
  src/app/setting.tsx
Labels: ♻️ refactor

#19 [Feat/#9] 선언적 에러 처리를 위한 error boundary 추가
  package.json
  pnpm-lock.yaml
Labels: good first issue, ✨ feature

#21 [Feat/#8] Safearea 라이브러리 추가
  src/app/_layout.tsx
Labels: ✨ feature

#20 [Feat/#16] git hook 도입(Feat: husky)
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: ✨ feature

#27 [Feat/#24] native 배포 스크립트 테스트
  .github/issue_template.md
  .github/pull_request_template.md
  .github/workflows/develop-cd.yml
  .github/workflows/label-checker.yml
  .github/workflows/preview-cd.yml
  .gitignore
  .npmrc
  .ruby-version
  app.config.js
  eas.json
  package.json
  pnpm-lock.yaml
Labels: build-native
